In [2]:
import numpy as np

В цьому домашньому завданні ми реалізуємо логістичну регресію на `numpy`.
Ці завдання допоможуть вам ґрунтовно засвоїти основні концепції логістичної регресії та реалізувати їх на практиці 🔥

#### Завдання 1: Реалізація функції сигмоїди
1. З використанням `numpy` напишіть функцію `sigmoid(z)` для обчислення значення сигмоїди згідно з формулою:
   $$
   \sigma(z) = \frac{1}{1 + e^{-z}}
   $$
2. Використовуючи цю функцію, обчисліть значення сигмоїди для наступних даних: $ z = [-2, -1, 0, 1, 2] $. Виведіть результат обчислень.


In [4]:
def sigmoid(x):
  return 1/(1 + np.power(np.e, -(x)))

print(sigmoid(np.array([-2,-1,0,1,2])))

[0.11920292 0.26894142 0.5        0.73105858 0.88079708]




#### Завдання 2: Реалізація функції гіпотези для логістичної регресії
1. Напишіть функцію `hypothesis(theta, X)`, яка обчислює гіпотезу для логістичної регресії, використовуючи функцію сигмоїди. Формула гіпотези:
   $$
   h_\theta(x) = \sigma(\theta^T x) = \frac{1}{1 + e^{-\theta^T x}}
   $$
2. Використайте функцію `hypothesis` для обчислення значень гіпотези для наступних даних:
   
   $\theta = [0.5, -0.5]$
   
   $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  Виведіть результат обчислень.


In [28]:
def hypothesis(theta, X):

  weighted_X = X @ theta.T

  return sigmoid(weighted_X)

test_theta = np.array([0.5, -0.5], ndmin=2)

test_X = np.array([[1,2],
                   [1,-1],
                   [1,0],
                   [1,1]
                   ])

print(hypothesis(test_theta,test_X ))

[[0.37754067]
 [0.73105858]
 [0.62245933]
 [0.5       ]]


#### Завдання 3: Реалізація функції для підрахунку градієнтів фукнції втрат
1. Напишіть функцію `compute_gradient(theta, X, y)`, яка обчислює градієнти функції втрат для логістичної регресії. Формула для обчислення градієнта:
   $$
   \frac{\partial L(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^{m} \left[ (h_\theta(x^{(i)}) - y^{(i)}) x_j^{(i)} \right]
   $$
2. Використайте функцію `compute_gradient` для обчислення градієнтів для наступних даних:

  $\theta = [0.5, -0.5]$

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Виведіть результат обчислень.

In [232]:
def compute_gradient(theta, X, y):
    m = X.shape[0]
    
    predictions = hypothesis(theta, X)
    
    #here we transpose y since predictions is a vecvtor mx1 and y on input is 1xm, and we get this wierd mxm vector when substract mx1 from 1xm
    error = predictions - y.T
    
    gradient = 1/m * (X.T @ error)
    
    return gradient

test_theta = np.array([0.5, -0.5], ndmin=2)

test_X = np.array([[1,2],
                   [1,-1],
                   [1,0],
                   [1,1]
                   ])

test_y = np.array([1,0,1,0], ndmin=2)

print(compute_gradient(test_theta,test_X,test_y))
    

[[ 0.05776464]
 [-0.36899431]]



#### Завдання 4: Реалізація повного батч градієнтного спуску

**Задача:**
1. Напишіть функцію `full_batch_gradient_descent(X, y, lr=0.1, epochs=100)`, яка реалізує алгоритм Full градієнтного спуску для логістичної регресії. Використовуйте такі формули:
   - Гіпотеза: $ h_\theta(x) = \sigma(\theta^T x) $
   - Оновлення параметрів: $ \theta_j := \theta_j - \alpha \frac{\partial L(\theta)}{\partial \theta_j} $
2. Використайте функцію `full_batch_gradient_descent` для обчислення параметрів моделі на наступних даних:

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Увага! Матриця $X$ вже має стовпець одиниць і передбачається, що це. - стовпець для intercept - параметра зсуву.

  Виведіть результат обчислень.


In [230]:
def full_batch_gradient_descent(X, y, lr=0.1, epochs=100):
    theta = np.random.randn(2,1).T
    
    for i in range(epochs):
        gradient = compute_gradient(theta,X,y)
        
        theta = theta - lr*gradient.T
    
    return theta

full_batch_gradient_descent(test_X, test_y)

array([[-0.11775849, -0.7085217 ]])

#### Завдання 5. Обчислення точності моделі

1. Напишіть функцію `predict_proba(theta, X)`, яка використовує знайдені параметри $\theta$ для обчислення ймовірностей належності поточного прикладу з даних до класу $y=1$ на основі значень $\sigma(\theta^T x)$.

2. Напишіть функцію `predict(theta, X, threshold=0.5)`, яка обчислює клас з передбаченої імовірності належності екземпляра до класу 1 з порогом 0.5. Тобто якщо ймовірність менше 0.5, то передбачаємо клас 0, інакше клас 1.

3. Напишіть функцію `accuracy(y_true, y_pred)`, яка обчислює точність моделі, визначивши частку правильно передбачених класів.

  Формула метрики Accuracy:
  $$
  \text{Accuracy} = \frac{\sum_{i=1}^{m} I(\hat{{y}^{(i)}} = y^{(i)})}{m}
  $$

  де $\hat{{y}^{(i)}}$ - передбачене значення класу, $I$ - індикаторна функція (яка дорівнює 1, якщо умова виконується, і 0 - якщо ні), $m$ - кількість прикладів.

4. Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

In [267]:
def predict_proba(theta, X):
    return hypothesis(theta, X)

def predict(theta, X, threshold=0.5):
    predictions = hypothesis(theta, X)
    
    return np.array([1 if prediction >=0.5 else 0 for prediction in predictions])

def accuracy(y_true, y_pred):
    m = y_true.shape[0]
    
    error = (y_true == y_pred).astype(int)
    
    return np.sum(error)/m

pred_theta = full_batch_gradient_descent(test_X, test_y, 0.001, 500)

predicted_y = predict(pred_theta, test_X)

model_accuracy = accuracy(predicted_y, test_y)

print("Predicted thetas: " ,pred_theta)
print("Predicted Ys: " ,predicted_y)
print("Model Accurasy is: ", model_accuracy)

Predicted thetas:  [[0.70401509 0.98914145]]
Predicted Ys:  [1 0 1 1]
Model Accurasy is:  0.75


Im not sure if this is possible to teach a model with such a small dataset, i tried different learining rate and amount of epochs, but is still looks more like guessing than like real prediction. Hence that it is hard to say if the code that i wrote is correct or no, but i tried to double check it and it seems ok to me.