In [1]:
import numpy as np

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [27]:
vector = np.random.rand(10)

matrix = np.array([
    [11,14,17],
    [20,23,26],
    [29,32,35]
])

vector,matrix,vector.shape,matrix.shape

(array([0.15442081, 0.35607912, 0.37347514, 0.653194  , 0.20350267,
        0.08035333, 0.82644439, 0.64485706, 0.00344543, 0.59894259]),
 array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (10,),
 (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [29]:
vector = np.round(vector + 10,2)

matrix = matrix * 2

new_vector = vector * vector

vector, matrix, new_vector

(array([10.15, 10.36, 10.37, 10.65, 10.2 , 10.08, 10.83, 10.64, 10.  ,
        10.6 ]),
 array([[22, 28, 34],
        [40, 46, 52],
        [58, 64, 70]]),
 array([103.0225, 107.3296, 107.5369, 113.4225, 104.04  , 101.6064,
        117.2889, 113.2096, 100.    , 112.36  ]))


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [31]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [41]:
result_matrix = np.dot(A.T, B.T)

display(result_matrix)

result_vector = np.dot(result_matrix, C)

display(result_vector)

new_matrix = np.dot(result_matrix, D)

display(new_matrix)

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

array([[0.2034],
       [0.2846]])

array([[0.2034, 0.7281],
       [0.2846, 0.5202]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [61]:
result_matrix_transposed = result_matrix.T

vector_transposed = vector.T

#the shape didnt change since the vector vas 1-dimensional, and within numpy logic it is not posible to transpose it
display(vector_transposed)

column_vector = np.expand_dims(vector, axis=1)

#here we can see that vector now changed from horisontal to vertical
display(vector, column_vector)

#and we also can see how the shape now has 2 dimensions
display(vector.shape, column_vector.shape)

#now we can see that column vector has two dimensions even though it was transposed back into horisontal.
#the main difference that we can see is that the array now is within another array
display(column_vector.T, column_vector.T.shape)


array([10.15, 10.36, 10.37, 10.65, 10.2 , 10.08, 10.83, 10.64, 10.  ,
       10.6 ])

array([10.15, 10.36, 10.37, 10.65, 10.2 , 10.08, 10.83, 10.64, 10.  ,
       10.6 ])

array([[10.15],
       [10.36],
       [10.37],
       [10.65],
       [10.2 ],
       [10.08],
       [10.83],
       [10.64],
       [10.  ],
       [10.6 ]])

(10,)

(10, 1)

array([[10.15, 10.36, 10.37, 10.65, 10.2 , 10.08, 10.83, 10.64, 10.  ,
        10.6 ]])

(1, 10)